import { Pet } from 'common/pets'

export const pets: Pet[] = [
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z5jdHi6B-myT',
        name: 'Maylon',
        age: 1.2,
        brand: 'Poodle',
        ownerName: 'Luke',
        ownerPhone: '(81)99256-3307',
        sex: 'Male',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Gato',
        id: 'V1StGXR8_Z6jdHi6B-myT',
        name: 'Jessica',
        age: 3.2,
        brand: 'Mixed',
        ownerName: 'Maria',
        ownerPhone: '(81)99256-3308',
        sex: 'Female',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z7jdHi6B-myT',
        name: 'Max',
        age: 2.5,
        brand: 'Labrador',
        ownerName: 'John',
        ownerPhone: '(81)99256-3309',
        sex: 'Male',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Gato',
        id: 'V1StGXR8_Z8jdHi6B-myT',
        name: 'Bella',
        age: 1.8,
        brand: 'Golden Retriever',
        ownerName: 'Sarah',
        ownerPhone: '(81)99256-3310',
        sex: 'Female',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Gato',
        id: 'V1StGXR8_Z9jdHi6B-myT',
        name: 'Charlie',
        age: 4.7,
        brand: 'German Shepherd',
        ownerName: 'Michael',
        ownerPhone: '(81)99256-3311',
        sex: 'Male',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Gato',
        id: 'V1StGXR8_Z10jdHi6B-myT',
        name: 'Lucy',
        age: 2.3,
        brand: 'Bulldog',
        ownerName: 'Emily',
        ownerPhone: '(81)99256-3312',
        sex: 'Female',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z11jdHi6B-myT',
        name: 'Rocky',
        age: 3.9,
        brand: 'Rottweiler',
        ownerName: 'David',
        ownerPhone: '(81)99256-3313',
        sex: 'Male',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z12jdHi6B-myT',
        name: 'Luna',
        age: 1.5,
        brand: 'Husky',
        ownerName: 'Olivia',
        ownerPhone: '(81)99256-3314',
        sex: 'Female',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z13jdHi6B-myT',
        name: 'Cooper',
        age: 2.1,
        brand: 'Beagle',
        ownerName: 'Daniel',
        ownerPhone: '(81)99256-3315',
        sex: 'Male',
    },
    {
        avatar: 'https://m.media-amazon.com/images/I/81Ski+fm4BL.png',
        type: 'Cachorro',
        id: 'V1StGXR8_Z14jdHi6B-myT',
        name: 'Molly',
        age: 4.2,
        brand: 'Cocker Spaniel',
        ownerName: 'Ava',
        ownerPhone: '(81)99256-3316',
        sex: 'Female',
    },
]

export const users = [
    {
        email: 'costa@email.com',
        password: '123',
    },
]
